FROM ghcr.io/foundry-rs/foundry:v1.1.0

USER root

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  curl \
  expect \
  jq \
  python3 \
  && rm -rf /var/cache/apt/*

# Install poetry manually because python3-poetry package is too old (1.1.12)
RUN curl -sSL https://install.python-poetry.org | python3 -

# Install Node.js because nodejs package is too old (v12.22.9)
# and "Error: Cannot find module 'node:crypto'" occurrs
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x nodesource_setup.sh | bash \
  && apt-get install --no-install-recommends -y nodejs

RUN git clone https://github.com/bnb-chain/bsc-genesis-contract -b develop /root/genesis \
    && cd /root/genesis && git checkout 44ebc6c17a00bd24db3240141a78091528dcebbb && npm ci

RUN cd /root/genesis && /root/.local/bin/poetry install
RUN cd /root/genesis && forge install --no-git foundry-rs/forge-std@v1.7.3

# override resources
COPY genesis/ /root/genesis/

COPY --from=bsc-geth:docker-local-arm64 /usr/local/bin/geth /usr/local/bin/geth
COPY --from=bsc-geth:docker-local-arm64 /go/bin/dlv /usr/local/bin/dlv

ENTRYPOINT [ "/bin/bash" ]
